const experiencia = [
  {
    id: 1,
    nombre_del_puesto: "Instalador",
    centro_de_trabajo: "Reantel S.L.",
    fecha_inicio: "09/2008",
    fecha_fin: "12/2008",
    ciudad: "Valladolid",
    pais: "España",
    descripcion:
      "Instalación y configuración de líneas RDSI, ADSL y Router CISCO.",
  },
  {
    id: 2,
    nombre_del_puesto: "Educador - Monitor",
    centro_de_trabajo: "Fundación Rondilla",
    fecha_inicio: "09/2007",
    fecha_fin: "06/2010",
    ciudad: "Valladolid",
    pais: "España",
    descripcion:
      "Profesor de Informática e Internet para adultos y taller PCPI en Reparación y Mantenimiento de Equipos Informáticos.",
  },
  {
    id: 3,
    nombre_del_puesto: "Desarrollador web",
    centro_de_trabajo: "Cosmomedia S.L.",
    fecha_inicio: "09/2012",
    fecha_fin: "12/2012",
    ciudad: "Valladolid",
    pais: "España",
    descripcion: "Programador web Back-End: ASP.NET.",
  },
  {
    id: 4,
    nombre_del_puesto: "Encargado Área de Informática",
    centro_de_trabajo: "Ayto. de Moho",
    fecha_inicio: "02/2013",
    fecha_fin: "12/2013",
    ciudad: "Moho,Puno",
    pais: "Perú",
    descripcion:
      "Mantenimiento, soporte y actualización de página web (CMS), equipos, CCTV y cableado estructurado.",
  },
  {
    id: 5,
    nombre_del_puesto: "Desarrollador de proyectos TIC",
    centro_de_trabajo: "Fodasat S.R.L.",
    fecha_inicio: "01/2014",
    fecha_fin: "03/2017",
    ciudad: "Puno",
    pais: "Perú",
    descripcion:
      "Elaboración de planos, instalación, configuración y mantenimiento de redes e Internet, CCTV, alarmas y sensores de movimiento.",
  },
  {
    id: 6,
    nombre_del_puesto: "Operario",
    centro_de_trabajo: "Renault España",
    fecha_inicio: "08/2017",
    fecha_fin: "08/2018",
    ciudad: "Valladolid",
    pais: "España",
    descripcion: "Operario en picking, checkman en cadena.",
  },
  {
    id: 7,
    nombre_del_puesto: "Operario",
    centro_de_trabajo: "Renault España",
    fecha_inicio: "02/2019",
    fecha_fin: "02/2020",
    ciudad: "Valladolid",
    pais: "España",
    descripcion: ["Operario en picking y cadena", "Checkman en cadena."],
  },
  {
    id: 8,
    nombre_del_puesto: "Operario",
    centro_de_trabajo: "Quesería Entrepinares, S.A.U.",
    fecha_inicio: "09/2020",
    fecha_fin: "08/2021",
    ciudad: "Valladolid",
    pais: "España",
    descripcion: [
      "Operario de maquinaria especializada en la producción de queso",
      "Limpieza y mantenimiento de maquinaria industrial.",
    ],
  },
  {
    id: 9,
    nombre_del_puesto: "Desarrollador web",
    centro_de_trabajo: "Fundación Intras",
    fecha_inicio: "06/2022",
    fecha_fin: "07/2022",
    ciudad: "Valladolid",
    pais: "España",
    descripcion: [
      "Desarrollo de página web utilizando Wordpress, Elementor y CSS3",
      "Migración web de Drupal a Wordpress.",
    ],
  },
  {
    id: 10,
    nombre_del_puesto: "Desarrollador web",
    centro_de_trabajo: "Freelance",
    fecha_inicio: "07/2022",
    fecha_fin: "12/2022",
    ciudad: "Valladolid",
    pais: "España",
    descripcion: [
      "Desarrollo de páginas y aplicaciones web, mantenimiento y soporte",
      "Utilización de IA como ChatGPT, GitHub Copilot y Leonardo IA para mejorar la eficiencia en el desarrollo web.",
    ],
  },
  {
    id: 11,
    nombre_del_puesto: "Technical Consultant",
    centro_de_trabajo: "Thirdera",
    fecha_inicio: "12/2022",
    fecha_fin: "06/2023",
    ciudad: "Valladolid",
    pais: "España",
    descripcion:
      "Desarrollo de soluciones ITSM y CSM con ServiceNow y utilizando JavaScript.",
  },
  {
    id: 12,
    nombre_del_puesto: "Tutor online",
    centro_de_trabajo: "EUSA S.L.U.",
    fecha_inicio: "03/2024",
    fecha_fin: "05/2024",
    ciudad: "Sevilla",
    pais: "España",
    descripcion:
      "Especialidad Formativa: Mantenimiento eléctrico y mecánico de instalaciones industriales (IMAI017PO)",
  },
  {
    id: 13,
    nombre_del_puesto: "Tutor online",
    centro_de_trabajo: "EUSA S.L.U.",
    fecha_inicio: "03/2024",
    fecha_fin: "04/2024",
    ciudad: "Sevilla",
    pais: "España",
    descripcion:
      "Especialidad Formativa: Instalación y Mantenimiento Industrial (IMAI018PO)",
  },
  {
    id: 14,
    nombre_del_puesto: "Tutor online",
    centro_de_trabajo: "CAMPUS CÁMARA S.A.",
    fecha_inicio: "05/2024",
    fecha_fin: "06/2024",
    ciudad: "Sevilla",
    pais: "España",
    descripcion:
      "Especialidad Formativa: Mantenimiento eléctrico y mecánico de instalaciones industriales (IMAI017PO)",
  },
  {
    id: 15,
    nombre_del_puesto: "Tutor online",
    centro_de_trabajo: "FEMXA",
    fecha_inicio: "05/2024",
    fecha_fin: "06/2024",
    ciudad: "Madrid",
    pais: "España",
    descripcion:
      "Módulo Formativo: Integración de componentes software en páginas web (IFCD0110)",
  },
  {
    id: 16,
    nombre_del_puesto: "Tutor online",
    centro_de_trabajo: "Hostelería de España",
    fecha_inicio: "07/2024",
    fecha_fin: "09/2024",
    ciudad: "Sevilla",
    pais: "España",
    descripcion:
      "Especialidad Formativa: Inteligencia Artificial Aplicada a la Empresa (IFCT163PO)",
  },
  {
    id: 17,
    nombre_del_puesto: "Docente de FP para el empleo",
    centro_de_trabajo: "GRUPO ASPASIA",
    fecha_inicio: "05/2024",
    fecha_fin: "10/2024",
    ciudad: "Valladolid",
    pais: "España",
    descripcion:
      "Certificado de Profesionalidad de Nivel 3: Desarrollo de Aplicaciones con Tecnologías Web (IFCD0210)",
  },
  {
    id: 18,
    nombre_del_puesto: "Desarrollador web",
    centro_de_trabajo: "Freelance",
    fecha_inicio: "07/2023",
    fecha_fin: "Actual",
    ciudad: "Valladolid",
    pais: "España",
    descripcion: [
      "Desarrollo de páginas y aplicaciones web, mantenimiento y soporte",
      "Utilización de IA como ChatGPT, GitHub Copilot y Leonardo IA para mejorar la eficiencia en el desarrollo web.",
    ],
  },
];
