const formacion_complementaria = [
  {
    id_fc: 1,
    nombre_formacion: "Docencia de la Formación Profesional",
    centro_formacion: "Grupo ASPASIA",
    cod_formacion: "SSCE0110",
    fecha_inicio: "12-2023",
    fecha_fin: "03-2024",
    ciudad: "Valladolid",
    modalidad: "Presencial",
    tipo_formacion: "Certificado de profesionalidad",
  },
  {
    id_fc: 2,
    nombre_formacion: "Formación de Formadores en E-Learning ",
    centro_formacion: "Grupo COLON-IECM",
    cod_formacion: "SSCE075PO",
    fecha_inicio: "11-2023",
    fecha_fin: "12-2023",
    ciudad: "Madrid",
    modalidad: "Online",
    tipo_formacion: "Especialidad Formativa",
  },
  {
    id_fc: 3,
    nombre_formacion: "Desarrollo de Aplicaciones con Tecnologías Web",
    centro_formacion: "Centro Formativo PLANFORM",
    cod_formacion: "IFCD0210",
    fecha_inicio: "02-2022",
    fecha_fin: "07-2022",
    ciudad: "Valladolid",
    modalidad: "Presencial",
    tipo_formacion: "Certificado de profesionalidad",
  },
];

const habilidades = [
  "HTML",
  "CSS",
  "Javascript",
  "React",
  "JQuery",
  "PHP",
  "MySQL",
  "Laravel",
  "Git",
  "GitHub",
  "WordPress",
  "WooCommerce",
  "ServiceNow",
  "ChatGPT",
  "LeonardoIA",
  "Github Copilot",
];
